name: resume-upload-action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  packages: write

jobs:
    deploy:
      runs-on: ubuntu-latest
      name: resume-push
      steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: connect to ec2 instance
        run: |
          echo ${{ secrets.EC2_SSH_KEY }} > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-3-90-166-99.compute-1.amazonaws.com '
              # Now we have got the access of EC2 and we will start the deploy .
              cd /home '
